### ISSUE TITLE
usage example in docs doesn't work and some Qs

### ISSUE THREAD

**Issue by trentm** [elastic/ecs-logging-ruby#12]
## basics docs example doesn't work

The example in the docs for using the ECS logger (https://www.elastic.co/guide/en/ecs-logging/ruby/current/setup.html#_configure) doesn't work:

```
% cat bar.rb
require 'ecs/logger'

logger = Ecs::Logger.new($stdout)
logger.info('my informative message')
logger.warn { 'be aware that…' }
logger.error('a_progname') { 'oh no!' }

% ruby bar.rb
Traceback (most recent call last):
	2: from bar.rb:1:in `<main>'
	1: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ecs/logger (LoadError)
```

That'll be because of commit de0ada19791ede906aa4abbbff5e20498b618591 that didn't update the README basic usage.

## question on hyphen/underscore in module name

I'm also confused on how to use this:

```
irb(main):001:0> require 'ecs-logging'
=> true
irb(main):002:0> require 'ecs_logging'
=> false
irb(main):003:0> require 'ecs_logging/logger'
=> true
```

Is it the intent that one does `gem install ecs-logging` (with a hyphen) and then uses it via `ecs_logging` (with an underscore)?

## logger.warn example doesn't work

If I "fix" (not sure I'm correct) the usage example:

```ruby
require 'ecs_logging/logger'

logger = EcsLogging::Logger.new($stdout)
logger.info('my informative message')
logger.warn { 'be aware that…' }    # <--- This fails
logger.error('a_progname') { 'oh no!' }
```

The warn example fails:

```
% ruby foo.rb
{"@timestamp":"2020-12-22T00:40:43.208Z","log.level":"INFO","message":"my informative message","ecs.version":"1.4.0"}
Traceback (most recent call last):
        1: from foo.rb:5:in `<main>'
/usr/local/lib/ruby/gems/2.7.0/gems/ecs-logging-0.2.0/lib/ecs_logging/logger.rb:60:in `block (2 levels) in <class:Logger>': wrong number of arguments (given 0, expected 1) (ArgumentError)
```

Is that because it requires a "message" for the ecs-logging spec? or some other reason?

**Comment by trentm** [comment]
@mikker @bmorelli25 ping

**Comment by mikker** [comment]
These are legit bugs. I'll fix, thanks!
